services:
  juje:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://poochie:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=juje2020
    depends_on:
      - poochie
  hobbit:
    build:
      context: ./reactme
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - juje
  poochie:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: juje2020

    ports:
      - "5432:5432"


